#goal definition
float64 start_pos
float64 end_pos
bool null_cmd
uint8 image_pub
string map_name
bool publish_trajectory
bool use_cmd_vel
float64 trajectory_horizon
---
#result definition
bool success
---
#feedback
